name: civis_local
services:
  civis_backend:
    container_name: civis_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      UVICORN_WORKERS: 4
    env_file:
      - .env              
    volumes:
      - civis_backend_data:/app/data
      

volumes:
  civis_backend_data:
    name: civis_backend_data
